### PR TITLE
Allow userids as mentions to avoid pinging

### PR DESCRIPTION
**Pull request by tellowkrinkle**
It's nice to be able to use bot commands that involve other users without constantly pinging them.  This allows direct userids to be used instead of mentions.

### CODE REVIEW

**Comment by tellowkrinkle** [comment]
Shit I'm on the wrong branch
Let me fix this

**Comment by NoxCaos** [comment]
Please, use master branch, development it not up to date

**Comment by tellowkrinkle** [comment]
Aand fixed!

**Comment by NoxCaos** [comment]
No, its not fixed. Use **master** branch

**Comment by tellowkrinkle** [comment]
Oh you want it on master?
Sorry

**Comment by NoxCaos** [comment]
Sorry, I am not using dev branch anymore, as I actually don't develop (add features) to this version of bot anymore. All I do is some fixes or small urgent improvements, so I use master for all just to save time

**Comment by tellowkrinkle** [comment]
Okay, it's back on master

**Comment by NoxCaos** [comment]
Alright, thank you for this
Update will be up once I test it

**Pull request merged**
