### PR TITLE
Bot now DMs if sending a normal message fails

### PR DESCRIPTION
**Pull request by tellowkrinkle**
People should at least know if their message fails to be responded to
Note: This will fail for people who have the "receive DMs from other people on the server" privacy option disabled.

### CODE REVIEW

**Comment by NoxCaos** [comment]
The problem is that there is no error at all. It seems like everything was sent okay, but its not
I don't know if catch will do something but I can try

**Comment by baiorin8356** [comment]
@NoxCaos You can `.catch()` any `.send()` in D.JS

**Comment by tellowkrinkle** [comment]
Ohh weird

**Comment by tellowkrinkle** [comment]
Well at least people will know if the server owner broke permissions on some channel

**Comment by NoxCaos** [comment]
I will commit this. But D.JS can go and suck a toblerone because next week this pile of useless dependencies will be gone from my bot
Thanks @tellowkrinkle

**Pull request merged**
